import { IconsCatalog } from '../models/enums/icons.enums.ts';
import { Account, TransactionMap } from '../models/types/mockData.types.ts';

export const mockAccounts: Account[] = [
  {
    id: 'acc001',
    name: 'Savings',
    number: '**** 1234',
    balance: 5025.5,
  },
  {
    id: 'acc002',
    name: 'Checking',
    number: '**** 5978',
    balance: 1842.75,
  },
  {
    id: 'acc003',
    name: 'Investment',
    number: '**** 8890',
    balance: 10987.3,
  },
  {
    id: 'acc004',
    name: 'Travel Fund',
    number: '**** 4321',
    balance: 800.0,
  },
];

export const mockTransactions: TransactionMap = {
  acc001: [
    {
      id: 'txn1',
      date: '2025-06-20',
      description: 'ATM Withdrawal',
      source: 'Downtown ATM',
      amount: -100.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn2',
      date: '2025-06-18',
      description: 'Deposit',
      source: 'Direct Deposit',
      amount: 500.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn3',
      date: '2025-06-16',
      description: 'Electric Bill',
      source: 'Monthly Utilities',
      amount: -120.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn4',
      date: '2025-06-15',
      description: 'Grocery Store',
      source: 'Walmart',
      amount: -65.2,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn5',
      date: '2025-06-14',
      description: 'Transfer from Checking',
      source: 'Checking Account',
      amount: 250.0,
      icon: IconsCatalog.AppleIcon,
    },
  ],
  acc002: [
    {
      id: 'txn6',
      date: '2025-06-19',
      description: 'Restaurant',
      source: 'Bella Italia',
      amount: -75.5,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn7',
      date: '2025-06-17',
      description: 'Salary',
      source: 'Company Inc.',
      amount: 2000.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn8',
      date: '2025-06-13',
      description: 'Online Shopping',
      source: 'Amazon',
      amount: -120.45,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn9',
      date: '2025-06-12',
      description: 'Water Bill',
      source: 'Utilities',
      amount: -40.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn10',
      date: '2025-06-10',
      description: 'Transfer to Savings',
      source: 'Savings Account',
      amount: -250.0,
      icon: IconsCatalog.AppleIcon,
    },
  ],
  acc003: [
    {
      id: 'txn11',
      date: '2025-06-20',
      description: 'Stock Dividend',
      source: 'Robinhood',
      amount: 320.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn12',
      date: '2025-06-15',
      description: 'Investment Deposit',
      source: 'Portfolio Fund',
      amount: 5000.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn13',
      date: '2025-06-10',
      description: 'ETF Purchase',
      source: 'iShares',
      amount: -2500.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn14',
      date: '2025-06-08',
      description: 'Bond Interest',
      source: 'Gov Bonds',
      amount: 80.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn15',
      date: '2025-06-06',
      description: 'Crypto Trade',
      source: 'Binance',
      amount: -100.0,
      icon: IconsCatalog.AppleIcon,
    },
  ],
  acc004: [
    {
      id: 'txn16',
      date: '2025-06-18',
      description: 'Airbnb Reservation',
      source: 'Lisbon, PT',
      amount: -300.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn17',
      date: '2025-06-17',
      description: 'Flight Booking',
      source: 'Lufthansa',
      amount: -200.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn18',
      date: '2025-06-14',
      description: 'Travel Deposit',
      source: 'Vacation Fund',
      amount: 800.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn19',
      date: '2025-06-10',
      description: 'Travel Insurance',
      source: 'Safety First',
      amount: -50.0,
      icon: IconsCatalog.AppleIcon,
    },
    {
      id: 'txn20',
      date: '2025-06-08',
      description: 'Currency Exchange',
      source: 'Revolut',
      amount: -40.0,
      icon: IconsCatalog.AppleIcon,
    },
  ],
};
